// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Movie {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    poster: { data: Media };
    releaseDate?: Date;
  };
}
export interface Movie_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  poster: Media_Plain;
  releaseDate?: Date;
}

export interface Movie_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  poster: number;
  releaseDate?: Date;
}

export interface Movie_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  poster: AdminPanelRelationPropertyModification<Media_Plain>;
  releaseDate?: Date;
}
