// Interface automatically generated by schemas-to-ts

import { Movie } from '../../../movie/content-types/movie/movie';
import { User } from '../../../../common/schemas-to-ts/User';
import { Movie_Plain } from '../../../movie/content-types/movie/movie';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Note {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    note: number;
    movie?: { data: Movie };
    users_permissions_user?: { data: User };
  };
}
export interface Note_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  note: number;
  movie?: Movie_Plain;
  users_permissions_user?: User_Plain;
}

export interface Note_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  note: number;
  movie?: number;
  users_permissions_user?: number;
}

export interface Note_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  note: number;
  movie?: AdminPanelRelationPropertyModification<Movie_Plain>;
  users_permissions_user?: AdminPanelRelationPropertyModification<User_Plain>;
}
